[package]
name = "examples"
version = "0.0.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
publish = false

# hello
[[bin]]
name = "hello-grpc-server"
path = "src/hello/grpc_server.rs"
[[bin]]
name = "hello-grpc-client"
path = "src/hello/grpc_client.rs"
[[bin]]
name = "hello-thrift-server"
path = "src/hello/thrift_server.rs"
[[bin]]
name = "hello-thrift-client"
path = "src/hello/thrift_client.rs"

# compression
[[bin]]
name = "compresion-grpc-server"
path = "src/compression/grpc_server.rs"
[[bin]]
name = "compression-grpc-client"
path = "src/compression/grpc_client.rs"

# multiplex
[[bin]]
name = "multiplex-grpc-server"
path = "src/multiplex/grpc_server.rs"
[[bin]]
name = "multiplex-grpc-client"
path = "src/multiplex/grpc_client.rs"

# streaming
[[bin]]
name = "streaming-grpc-server"
path = "src/streaming/grpc_server.rs"
[[bin]]
name = "streaming-grpc-client"
path = "src/streaming/grpc_client.rs"

# graceful shutdown
[[bin]]
name = "graceful-shutdown-server"
path = "src/graceful-shutdown/grpc_server.rs"
[[bin]]
name = "graceful-shutdown-client"
path = "src/graceful-shutdown/grpc_client.rs"

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
lazy_static.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tracing.workspace = true

pilota.workspace = true
volo = { path = "../volo" }
volo-grpc = { path = "../volo-grpc" }
volo-thrift = { path = "../volo-thrift" }

volo-gen = { path = "./volo-gen" }
